logLevel: INFO
period: 3000 # (milliseconds)
output: 'world/markers.json'
timestamp: 'yyyyMMdd HH:mm:ss'
markers:
    - OnlinePlayers
    - OfflinePlayers
OnlinePlayers:
    hideSneaking: false
OfflinePlayers:
    storage: 'OfflinePlayers.bin' # Store last location between restarts
SignChanges:
    clean: 172800000 # (milliseconds)
    storage: 'SignChanges.bin' # Store new sign data between restarts
version: @VERSION@
