period: 3000 # Every 3 seconds (milliseconds)
output: 'world/markers.json'
timestamp: 'yyyyMMdd HH:mm:ss'
logLevel: INFO
markers:
    - OnlinePlayers
    - OfflinePlayers
OfflinePlayers:
    storage: 'OfflinePlayers.bin' # Store last location between restarts
SignChanges:
    clean: 172800000 # Purge markers after 48 hours (milliseconds)
    storage: 'SignChanges.bin' # Store new sign data between restarts
    filters:
        FilterGroupExample:
            text1: 'regex'
            text2: 'regex'
            text3: 'regex'
            text4: 'regex'
    worlds:
        exampleWorldName:
            - FilterGroupExample
